const initialGenres = [
    { name: 'Action', selected: false, id: 'g1', emoji: '💥' },
    { name: 'Adventure', selected: false, id: 'g2', emoji: '🪂' },
    { name: 'Adult', selected: false, id: 'g3', emoji: '🔞' },
    { name: 'Animation', selected: false, id: 'g4', emoji: '🖍️' },
    { name: 'Biography', selected: false, id: 'g5', emoji: '📚' },
    { name: 'Bollywood ', selected: false, id: 'g6', emoji: '💃' },
    { name: 'Comedy', selected: false, id: 'g7', emoji: '😂' },
    { name: 'Crime', selected: false, id: 'g8', emoji: '🕵' },
    { name: 'Disaster', selected: false, id: 'g9', emoji: '☄️' },
    { name: 'Documentary', selected: false, id: 'g10', emoji: '🎥' },
    { name: 'Drama', selected: false, id: 'g11', emoji: '🎭' },
    { name: 'Family', selected: false, id: 'g12', emoji: '👪' },
    { name: 'Fantasy', selected: false, id: 'g13', emoji: '🦄' },
    { name: 'Film-Noir', selected: false, id: 'g14', emoji: '🎞' },
    { name: 'History', selected: false, id: 'g15', emoji: '📜' },
    { name: 'Horror', selected: false, id: 'g16', emoji: '🧟' },
    { name: 'Game-Show', selected: false, id: 'g17', emoji: '🎲' },
    { name: 'Independent', selected: false, id: 'g18', emoji: '📢' },
    { name: 'International', selected: false, id: 'g19', emoji: '🌎' },
    { name: 'Music', selected: false, id: 'g20', emoji: '🎧' },
    { name: 'Musical', selected: false, id: 'g21', emoji: '🎶' },
    { name: 'Mystery', selected: false, id: 'g22', emoji: '🔎' },
    { name: 'News', selected: false, id: 'g23', emoji: '📰' },
    { name: 'Reality-TV', selected: false, id: 'g24', emoji: '📺' },
    { name: 'Romance', selected: false, id: 'g25', emoji: '❤️' },
    { name: 'Rom-Com', selected: false, id: 'g26', emoji: '💏' },
    { name: 'Sci-Fi', selected: false, id: 'g27', emoji: '👽' },
    { name: 'Talk-Show', selected: false, id: 'g28', emoji: '🗣' },
    { name: 'Short', selected: false, id: 'g29', emoji: '⏳' },
    { name: 'Sport', selected: false, id: 'g30', emoji: '🏈' },
    { name: 'Thriller ', selected: false, id: 'g31', emoji: '😱' },
    { name: 'War ', selected: false, id: 'g32', emoji: '⚔️' },
    { name: 'Western ', selected: false, id: 'g33', emoji: '🤠' },
];

export default initialGenres;
