const initialGenres = [
    { name: '💥 Action', selected: false, id: 'g1' },
    { name: '🪂 Adventure', selected: false, id: 'g2' },
    { name: '🔞 Adult', selected: false, id: 'g3' },
    { name: '🖍️ Animation', selected: false, id: 'g4' },
    { name: '📚 Biography', selected: false, id: 'g5' },
    { name: '💃 Bollywood ', selected: false, id: 'g6' },
    { name: '😂 Comedy', selected: false, id: 'g7' },
    { name: '🕵 Crime', selected: false, id: 'g8' },
    { name: '☄️ Disaster', selected: false, id: 'g9' },
    { name: '🎥 Documentary', selected: false, id: 'g10' },
    { name: '🎭 Drama', selected: false, id: 'g11' },
    { name: '👪 Family', selected: false, id: 'g12' },
    { name: '🦄 Fantasy', selected: false, id: 'g13' },
    { name: '🎞 Film-Noir', selected: false, id: 'g14' },
    { name: '📜 History', selected: false, id: 'g15' },
    { name: '🧟 Horror', selected: false, id: 'g16' },
    { name: '🎲 Game-Show', selected: false, id: 'g17' },
    { name: '📢 Independent', selected: false, id: 'g18' },
    { name: '🌎 International', selected: false, id: 'g19' },
    { name: '🎧 Music', selected: false, id: 'g20' },
    { name: '🎶 Musical', selected: false, id: 'g21' },
    { name: '🔎 Mystery', selected: false, id: 'g22' },
    { name: '📰 News', selected: false, id: 'g23' },
    { name: '📺 Reality-TV', selected: false, id: 'g24' },
    { name: '❤️ Romance', selected: false, id: 'g25' },
    { name: '💏 Rom-Com', selected: false, id: 'g26' },
    { name: '👽 Sci-Fi', selected: false, id: 'g27' },
    { name: '🗣 Talk-Show', selected: false, id: 'g28' },
    { name: '⏳ Short', selected: false, id: 'g29' },
    { name: '🏈 Sport', selected: false, id: 'g30' },
    { name: '😱 Thriller ', selected: false, id: 'g31' },
    { name: '⚔️ War ', selected: false, id: 'g32' },
    { name: '🤠 Western ', selected: false, id: 'g33' },
];

export default initialGenres;
