const suggestedMovies = [
    {
        id: 1,
        selected: false,
        title: 'The Shawshank Redemption',
        releaseYear: 1994,
        poster: 'https://m.media-amazon.com/images/I/81O1wR9ohtL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 2,
        selected: false,
        title: 'Inception',
        releaseYear: 2010,
        poster: 'https://m.media-amazon.com/images/I/81UOFL9v79L._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 3,
        selected: false,
        title: 'The Intouchables',
        releaseYear: 2011,
        poster: 'https://m.media-amazon.com/images/I/813RpC1inEL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 4,
        selected: false,
        title: 'WALL-E',
        releaseYear: 2008,
        poster: 'https://m.media-amazon.com/images/I/91vYNYvKXvL._AC_UL480_FMwebp_QL65_.jpg',
    },
    {
        id: 5,
        selected: false,
        title: 'Flipped',
        releaseYear: 2010,
        poster: 'https://m.media-amazon.com/images/I/81ts3Y5pfDL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 6,
        selected: false,
        title: 'The Dark Knight',
        releaseYear: 2008,
        poster: 'https://m.media-amazon.com/images/I/91ebheNmoUL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 7,
        selected: false,
        title: 'Life of Pi',
        releaseYear: 2012,
        poster: 'https://m.media-amazon.com/images/I/81sQpouz82L._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 8,
        selected: false,
        title: 'The Pianist',
        releaseYear: 2003,
        poster: 'https://m.media-amazon.com/images/I/71A47Ju3NqL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 9,
        selected: false,
        title: 'The Godfather',
        releaseYear: 1972,
        poster: 'https://m.media-amazon.com/images/I/714ZOEiVNtL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 10,
        selected: false,
        title: 'The Godfather Part II',
        releaseYear: 1974,
        poster: 'https://m.media-amazon.com/images/I/71Tn5ZErDiL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 11,
        selected: false,
        title: '12 Angry Men',
        releaseYear: 1957,
        poster: 'https://m.media-amazon.com/images/I/71FthvsNDDL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 12,
        selected: false,
        title: "Schindler's list",
        releaseYear: 1994,
        poster: 'https://m.media-amazon.com/images/I/81pBGFSSSwL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 13,
        selected: false,
        title: 'The Lord of the Rings: The Return of the King',
        releaseYear: 2003,
        poster: 'https://m.media-amazon.com/images/I/912lTyxLdSL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 14,
        selected: false,
        title: 'Pulp Fiction',
        releaseYear: 1994,
        poster: 'https://m.media-amazon.com/images/I/81wrPiZFKIL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 15,
        selected: false,
        title: 'The Lord of the Rings: The Fellowship of the Ring',
        releaseYear: 2001,
        poster: 'https://m.media-amazon.com/images/I/91AbJ-7DqfL._AC_UY327_FMwebp_QL65_.jpg',
    },
    {
        id: 16,
        selected: false,
        title: 'Forrest Gump',
        releaseYear: 1994,
        poster: 'https://m.media-amazon.com/images/I/71nGjvTg15L._AC_UY327_FMwebp_QL65_.jpg',
    },
];

export default suggestedMovies;
