name: Deploy to Vercel

on:
  push:
    branches:
      - "**"  # Trigger on any branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Next.js project, including Stripe Publishable Key
      - name: Build project
        env:
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}  # Pass Stripe key to build
        run: npm run build

      # Deploy to Vercel using Vercel CLI and API token
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
