name: Deploy to Vercel

# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies (you can use npm or yarn)
      - name: Install dependencies
        run: npm install

      # Build the Next.js project
      - name: Build project
        run: npm run build

      # Deploy to Vercel using the API token stored in GitHub Secrets
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          curl -X POST https://api.vercel.com/v1/deployments \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -d "{\"name\":\"reeltalk-web\",\"gitSource\":{\"type\":\"github\",\"repoId\":\"reel-talk/reeltalk-web\"}}"
